package tv.own.owntv.features.settings

import tv.own.owntv.R

/*
 * The words of each Settings row on a Stage page (P10), by row key: root rows by their own key
 * ("theme", "tab_SOURCES"), Video player rows by their Quick key ("vp_hw"), Recording rows by "rec_*".
 * A row's own title and description are used wherever a key is missing here; a long description
 * the row used to carry becomes its panel text when [SETTING_HELP] has nothing better.
 */

/** The short line under the title (the mockup's wording). */
internal val SETTING_LINE: Map<String, Int> = mapOf(
    "quick_live_preview" to R.string.settings_line_quick_live_preview,
    "quick_preview_sound" to R.string.settings_line_preview_sound,
    "quick_channel_numbers" to R.string.settings_line_quick_channel_numbers,
    "quick_hdr" to R.string.settings_line_hdr,
    "quick_autoplay" to R.string.settings_line_quick_autoplay,
    "quick_check_update" to R.string.settings_line_when_app_opens,
    "epg_offset" to R.string.settings_line_epg_offset,
    "reminders" to R.string.settings_line_reminders,
    "reminder_lead" to R.string.settings_line_reminder_lead,
    "guide_days" to R.string.settings_line_guide_days,
    "catchup" to R.string.settings_line_catchup,
    "catchup_sources" to R.string.settings_line_catchup_sources,
    "accent" to R.string.settings_line_accent,
    "tab_GLASS_EFFECT" to R.string.settings_line_glass_bg,
    "fonts" to R.string.settings_line_fonts,
    "popup_size" to R.string.settings_line_popup_size,
    "animations" to R.string.settings_line_animations,
    "tab_WEATHER" to R.string.settings_line_weather,
    "live_opens_in" to R.string.settings_line_live_opens_in,
    "vod_layout" to R.string.settings_line_vod_layout,
    "tab_PANEL_WIDTH" to R.string.settings_line_panel_width,
    "tab_GUIDE_WIDTH" to R.string.settings_line_guide_width,
    "browsing_lists" to R.string.settings_line_browsing,
    "tab_HOME" to R.string.settings_line_home,
    "tab_CONTENT_MENUS" to R.string.settings_line_content_menus,
    "tab_CH_NAV" to R.string.settings_line_remote_shortcuts,
    "tab_CUSTOMIZE" to R.string.settings_line_customize,
    "tab_METADATA" to R.string.settings_line_metadata,
    "tab_OPEN_SUBTITLES" to R.string.settings_line_open_subtitles,
    "app_icon" to R.string.settings_line_app_icon,
    "brand_accent" to R.string.settings_line_brand_accent,
    "check_updates" to R.string.settings_line_check_updates,
    "update_startup" to R.string.settings_line_when_app_opens,
    "tab_NETWORK" to R.string.settings_line_proxy,
    "tab_DNS" to R.string.settings_line_dns,
    "vp_live_engine" to R.string.settings_line_live_engine,
    "vp_live_engine_sources" to R.string.settings_line_override_playlist,
    "vp_reset_live_pins" to R.string.settings_line_saved_live_choices,
    "vp_vod_engine" to R.string.settings_line_vod_engine,
    "vp_vod_engine_sources" to R.string.settings_line_override_playlist,
    "vp_reset_pins" to R.string.settings_line_saved_choices,
    "vp_forget_fixes" to R.string.settings_line_learned_fixes,
    "vp_external" to R.string.settings_line_external,
    "vp_vod_buffer" to R.string.settings_line_vod_buffer,
    "vp_vod_timeout" to R.string.settings_line_vod_timeout,
    "vp_vod_reconnects" to R.string.settings_line_vod_reconnects,
    "vp_hw" to R.string.settings_line_hw,
    "vp_hdr" to R.string.settings_line_hdr,
    "vp_max_quality" to R.string.settings_line_max_quality,
    "vp_tunneled" to R.string.settings_line_tunneled,
    "vp_zoom" to R.string.settings_line_zoom,
    "vp_reset_zoom" to R.string.settings_line_saved_zoom,
    "vp_afr" to R.string.settings_vp_cat_frame_rate_summary,
    "vp_afr_pause" to R.string.settings_line_films_only,
    "vp_afr_resolution" to R.string.settings_line_films_only,
    "vp_volume" to R.string.settings_line_volume,
    "vp_reset_volume" to R.string.settings_line_saved_volume,
    "vp_surround" to R.string.settings_line_surround,
    "vp_passthrough" to R.string.settings_line_passthrough,
    "vp_night_mode" to R.string.settings_line_night_mode,
    "vp_volume_leveling" to R.string.settings_line_leveling,
    "vp_audio_sync" to R.string.settings_line_audio_sync,
    "vp_reset_audio_delay" to R.string.settings_line_saved_audio_sync,
    "vp_audio_lang" to R.string.settings_line_audio_lang,
    "vp_sub_lang" to R.string.settings_line_sub_lang,
    "vp_sub_style" to R.string.settings_line_sub_style,
    "vp_channel_numbers" to R.string.settings_line_channel_numbers,
    "vp_live_preview" to R.string.settings_line_live_preview,
    "vp_preview_audio" to R.string.settings_line_preview_sound,
    "vp_timeshift" to R.string.settings_line_timeshift,
    "vp_timeshift_window" to R.string.settings_line_timeshift_window,
    "vp_live_left_right" to R.string.settings_line_left_right,
    "vp_live_latency" to R.string.settings_line_latency,
    "vp_latency_sources" to R.string.settings_line_override_playlist,
    "vp_preroll" to R.string.settings_line_preroll,
    "vp_preroll_sources" to R.string.settings_line_override_playlist,
    "vp_tune_timeout" to R.string.settings_line_tune_timeout,
    "vp_tune_timeout_sources" to R.string.settings_line_override_playlist,
    "vp_seek_step" to R.string.settings_line_seek_step,
    "vp_rewind_step" to R.string.settings_line_rewind_step,
    "vp_resume" to R.string.settings_line_resume,
    "vp_autoplay" to R.string.settings_line_autoplay,
    "vp_multiview" to R.string.settings_vp_cat_multiview_summary_mobile,
    "vp_multiview_tiles" to R.string.settings_line_tiles,
    "vp_mini" to R.string.settings_line_mini,
    "vp_measured_stats" to R.string.settings_line_measured_stats,
    "vp_logging" to R.string.settings_line_logging,
    "rec_reserve" to R.string.settings_line_rec_reserve,
    "rec_watching" to R.string.settings_line_rec_watching,
    "rec_pre_roll" to R.string.settings_line_rec_pre_roll,
    "rec_post_roll" to R.string.settings_line_rec_post_roll,
)

/** A row's name where the page words it differently from the app's older screens. */
internal val SETTING_TITLE: Map<String, Int> = mapOf(
    "fonts" to R.string.settings_title_fonts,
    "tab_WEATHER" to R.string.settings_title_date_time_weather,
    "vp_reset_live_pins" to R.string.settings_title_saved_live_choices,
    "vp_reset_pins" to R.string.settings_title_saved_choices,
    "vp_forget_fixes" to R.string.settings_title_learned_fixes,
    "vp_tunneled" to R.string.settings_title_tunneled,
    "vp_reset_zoom" to R.string.settings_title_saved_zoom,
    "vp_reset_volume" to R.string.settings_title_saved_volume,
    "vp_reset_audio_delay" to R.string.settings_title_saved_audio_sync,
)

/** The context panel's explanation, where the row's own description is not already one. */
internal val SETTING_HELP: Map<String, Int> = mapOf(
    "quick_live_preview" to R.string.settings_help_live_preview,
    "quick_preview_sound" to R.string.settings_help_preview_audio,
    "quick_channel_numbers" to R.string.settings_help_channel_numbers,
    "quick_check_update" to R.string.settings_help_update_startup,
    "tab_SOURCES" to R.string.settings_help_playlists,
    "tab_EPG" to R.string.settings_help_epg_sources,
    "epg_offset" to R.string.settings_epg_offset_root_description,
    "reminders" to R.string.settings_reminders_description,
    "reminder_lead" to R.string.settings_reminder_lead_description,
    "guide_days" to R.string.settings_help_guide_days,
    "catchup" to R.string.settings_help_catchup,
    "catchup_sources" to R.string.settings_catchup_timezone_per_playlist_description,
    "theme" to R.string.settings_help_theme,
    "accent" to R.string.settings_help_accent,
    "focus_highlight" to R.string.settings_help_focus,
    "tab_GLASS_EFFECT" to R.string.settings_help_bg_background,
    "fonts" to R.string.settings_help_fonts,
    "popup_size" to R.string.settings_help_popup_size,
    "ui_zoom" to R.string.settings_help_zoom,
    "animations" to R.string.settings_help_animations,
    "tab_WEATHER" to R.string.settings_help_weather,
    "navigation" to R.string.settings_help_navigation,
    "live_layout" to R.string.settings_help_live_layout,
    "live_opens_in" to R.string.settings_live_opens_in_description,
    "vod_layout" to R.string.settings_help_vod_layout,
    "tab_PANEL_WIDTH" to R.string.settings_panel_width_description,
    "tab_GUIDE_WIDTH" to R.string.settings_guide_width_description,
    "browsing_lists" to R.string.settings_browsing_description,
    "tab_HOME" to R.string.settings_help_home,
    "tab_CONTENT_MENUS" to R.string.settings_content_menus_description,
    "tab_CH_NAV" to R.string.settings_ch_paging_description,
    "tab_CUSTOMIZE" to R.string.settings_help_customize,
    "tab_METADATA" to R.string.settings_metadata_root_description,
    "tab_OPEN_SUBTITLES" to R.string.settings_open_subtitles_description,
    "app_icon" to R.string.settings_help_app_icon,
    "brand_accent" to R.string.settings_help_brand_accent,
    "app_startup" to R.string.settings_help_startup,
    "check_updates" to R.string.settings_help_check_updates,
    "update_startup" to R.string.settings_help_update_startup,
    "tab_NETWORK" to R.string.settings_proxy_description,
    "tab_DNS" to R.string.settings_help_dns,
    "vp_live_engine" to R.string.settings_help_live_engine,
    "vp_hw" to R.string.settings_help_hw,
    "vp_zoom" to R.string.settings_help_zoom_mode,
    "vp_volume" to R.string.settings_help_volume,
    "vp_sub_lang" to R.string.settings_help_sub_lang,
    "vp_channel_numbers" to R.string.settings_help_channel_numbers,
    "vp_live_preview" to R.string.settings_help_live_preview,
    "vp_preview_audio" to R.string.settings_help_preview_audio,
    "vp_timeshift_window" to R.string.settings_help_timeshift_window,
    "vp_seek_step" to R.string.settings_help_seek_step,
    "vp_resume" to R.string.settings_help_resume,
    "vp_mini" to R.string.settings_help_mini,
)

/** For a switch row, whether On is the recommended value (the panel tags it). Absent = no tag. */
internal val SWITCH_RECOMMENDED: Map<String, Boolean> = mapOf(
    "vp_hw" to true,
    "vp_measured_stats" to false,
    "vp_logging" to false,
    "rec_reserve" to true,
)
